### PR TITLE
Get the project up and running

### PR DESCRIPTION
**Pull request by bk203**
* Fixed various copy past classes
* Update composer.json with missing json extension
* Update composer.json increasing php version from 7.1 to 7.2 as dependencies require 7.2
* Update the composer.lock in general and with above changes
* Update README as assatic or assets are no longer used
* Apply some PSR2 code convention
* Remove unused and conflicting duplicate class BeerProjection
* Add missing projections to reset command

### CODE REVIEW

**Comment by bk203** [comment]
Found your online presentation about CQRS and Event Sourcing and wanted to try your project. Except I couldn't get it to work as Symfony had multiple issues, after some trail and error I fixed some issues and got it to work.

Hope you have the time to review my changes and possibly merge this, for other future users :D

**Comment by webbaard** [comment]
Hi bk203,

Thank for trying out my project, hoped you liked the presentation and the code wasn't to bad.

The thing is that I have a lot of code locally on my laptop that I still want to merge myself with a lot of fixes that I just didn't find time for yet. I will definitely look at your code to see if I can find any improvement but I can't promise a merge will happen. I hope you can try out my fixes when I push them (any possible improvement is welcome)

**Comment by bk203** [comment]
Thx for your reaction, I didn't assume the project was still maintained (so gave it a shot). Great that I can expect more from this project, will keep it on watch 👍.

**Comment by webbaard** [comment]
I was able to merge everything but did make some small changes in my own branch.
great to see people equally look at it so I sort of have to continue ;-)

**Comment by webbaard** [comment]
You should check the readme I've added some command to keep your projection up to date when adding, removing beer

**Pull request merged**
